services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  item_service:
    build: ./item_service
    
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    depends_on:
      - mongodb

  auth_service:
    build: ./auth_service
    
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    depends_on:
      - mongodb

  gui_service:
    build: ./gui_service
    ports:
      - "8501:8501"
    environment:
      - GATEWAY_URL=http://dispatcher:8000
    depends_on:
      - dispatcher

  bid_service:
    build: ./bid_service
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    
    depends_on:
      - mongodb

  dispatcher:
    build: ./dispatcher
    ports:
      - "8000:8000" 
    environment:
      - ITEM_SERVICE_URL=http://item_service:8001
      - AUTH_SERVICE_URL=http://auth_service:8002
    depends_on:
      - item_service
      - auth_service
  locust:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://dispatcher:8000
    ports:
      - "8089:8089"
    depends_on:
      - dispatcher
      
volumes:
  mongo_data: