services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  item_service:
    build: ./item_service
    # ports: - "8001:8001" SİLDİK (İzolasyon sağlandı)
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    depends_on:
      - mongodb

  auth_service:
    build: ./auth_service
    # ports: - "8002:8002" SİLDİK (İzolasyon sağlandı)
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    depends_on:
      - mongodb

  dispatcher:
    build: ./dispatcher
    ports:
      - "8000:8000" # Sadece bu kapı dış dünyaya açık
    environment:
      - ITEM_SERVICE_URL=http://item_service:8001
      - AUTH_SERVICE_URL=http://auth_service:8002
    depends_on:
      - item_service
      - auth_service

volumes:
  mongo_data: